### ISSUE TITLE
Discussion: implementation

### ISSUE THREAD

**Issue by leaxoy** [charliermarsh/ruff-lsp#29]
This plugin is great and help me a lot on python development, but I have a question, why this implement in python instead of rust, is it because there are some advantages?

Since the core ruff functions implement in rust. Maybe use rust is more consistent?

**Comment by charliermarsh** [comment]
I've considered this and I may move it to Rust eventually. It was helpful for me to do the LSP in Python to start since I'm relatively unfamiliar with the Language Server Protocol itself, and learning it in Python was easier for me.

There are a few other reasons that it may not be a good idea to port it to Rust:

1. I don't think performance is as important, especially because the LSP is a long-lived server, and so startup time isn't a huge problem.
2. I'd still want the server to be `pip install`-able, like Ruff -- which is solvable (as in Ruff), but more tedious as I'd have to build native wheels.
3. It's unlikely that I'd want to bundle Ruff itself, and call it directly as a library, because we need to be able to use any Ruff binary that the user wants. They might have Ruff installed in a different interpreter, on a different patch, etc. -- and we have to support all of those. So we'd likely need to have roughly the same setup, where we invoke Ruff over a subprocess in some cases.

I probably will move to Rust eventually for consistency, but this at least outlines why the benefits aren't _as_ appealing as for Ruff itself.
