### ISSUE TITLE
textDocument/definition is not supported

### ISSUE THREAD

**Issue by krims0n32** [charliermarsh/ruff-lsp#57]
I installed ruff-lsp through mason in Neovim but get this message when trying to go to a definition. Any ideas? I configured per the example in the docs.

LspInfo shows ruff-lsp is attached to the buffer and warnings like line too long do show up in the editor.

**Comment by charliermarsh** [comment]
We don't currently support go-to definition, if that's the question underlying the issue :) `ruff-lsp` only handles integration with Ruff, so surfacing errors and providing actions to correct them. It's recommended that you use `ruff-lsp` with some other Python LSP in order to get go-to definition or other behaviors. But please let me know if I'm misinterpreting.

**Comment by krims0n32** [comment]
Gotcha, that was my question :)
